### ISSUE TITLE
whats the entry point of this project?

### ISSUE THREAD

**Issue by bagherfathi** [chili-epfl/Trend-Detection#1]

**Comment by bagherfathi** [comment]
I want to setup a development environment and run and test this project. whats the entry point of this project? (required package and versions, which file and function is the starting point)?

**Comment by KhalilMrini** [comment]
Hi, sorry for the late reply, I just saw this issue.
You would have to install the required packages in the readme, and run the files in the order that they are shown in the readme. You may have to get your own Adzuna credentials to get data.
Thank you so much for your interest in our work!
